version: '3.8'

services:
  authdb:
    container_name: postgres-prod
    image: postgres:17
    environment:
      POSTGRES_USER: tacauthuser
      POSTGRES_PASSWORD: tacauthpass
      PGDATA: /authdb/data/postgres
      POSTGRES_DB: taccaseauth
    volumes:
      - authdb_data:/var/docker/taccaseauth
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    networks:
      - backend
#    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    profiles:
      - production

  authdb-dev:
    container_name: postgres-dev
    image: postgres:17
    environment:
      POSTGRES_USER: tacauthuser
      POSTGRES_PASSWORD: tacauthpass
      PGDATA: /authdb-dev/data/postgres
      POSTGRES_DB: taccaseauth
    volumes:
      - /dev/null:/var/docker/data/taccaseauth_dev
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "6433:5432"  # Different port for dev to avoid conflicts
    networks:
      - backend
#    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 3s
      retries: 3
    profiles:
      - development

  authorization-server:
    container_name: tac-case-auth-server-prod
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      SERVER_PORT: 8080  # Explicitly set the server's listening port
      AUTH_SERVER_ISSUER: http://localhost:8080  # Set the issuer URI to match the port
      SPRING_DATASOURCE_URL: jdbc:postgresql://authdb:5432/taccaseauth
      SPRING_DATASOURCE_USERNAME: tacauthuser  # Use $DB_USERNAME for consistency
      SPRING_DATASOURCE_PASSWORD: tacauthpass  # Use $DB_PASSWORD for consistency
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9081:8080"
    depends_on:
      authdb:
        condition: service_healthy
    networks:
      - backend
#    restart: unless-stopped
    profiles:
      - production

  authorization-server-dev:
    container_name: tac-case-auth-server-dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      SERVER_PORT: 8080  # Explicitly set the server's listening port
      AUTH_SERVER_ISSUER: http://localhost:8080  # Set the issuer URI to match the port
      SPRING_DATASOURCE_URL: jdbc:postgresql://authdb-dev:5432/taccaseauth
      SPRING_DATASOURCE_USERNAME: tacauthuser
      SPRING_DATASOURCE_PASSWORD: tacauthpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9082:8080"  # Different port for dev to avoid conflicts
    depends_on:
      authdb-dev:  # Reference the dev database
        condition: service_healthy
    networks:
      - backend
#    restart: unless-stopped
    profiles:
      - development

networks:
  backend:
    driver: bridge

volumes:
  authdb_data:

