#logging:
#  level:
#    org:
#      springdoc:
#        api:
#          OpenApiResource: info
#    web: info
spring:
  application:
    name: tac-case-auth-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taccaseapi}
    username: ${SPRING_DATASOURCE_USERNAME:tacapiuser}
    password: ${SPRING_DATASOURCE_PASSWORD:tacapipass}
  shell:
    interactive:
      enabled: true
  security:
    oauth2:
      authorizationserver:
        endpoint:
          token-uri:
        client:
          tac-case-api-client:
            registration:
              client-id: client-id
              client-secret: client-secret
              client-name: client-name
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client-credentials"
              scopes:
                - "read.cases"
                - "write.cases"

logging:
  level:
    root: warn
    org.jline: debug
    org.springframework.shell: info
    com.beaconstrategists: debug
    org.springframework.security: debug
#    org.springframework.security.oauth2.server.authorization: debug DO NOT SET THIS!
